name: Deploy to neocities

# only run on changes to main
on:
  workflow_dispatch:
  push:
    branches:
      - master
    # only run deploys when public changes
    paths:
      - 'public_splash/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v1.1.17
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: public_splash
